/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/best-racket`; params?: Router.UnknownInputParams; } | { pathname: `/compare-rackets`; params?: Router.UnknownInputParams; } | { pathname: `/faq`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/index_new`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/racket-detail`; params?: Router.UnknownInputParams; } | { pathname: `/rackets`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/best-racket`; params?: Router.UnknownOutputParams; } | { pathname: `/compare-rackets`; params?: Router.UnknownOutputParams; } | { pathname: `/faq`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/index_new`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/racket-detail`; params?: Router.UnknownOutputParams; } | { pathname: `/rackets`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/best-racket${`?${string}` | `#${string}` | ''}` | `/compare-rackets${`?${string}` | `#${string}` | ''}` | `/faq${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/index_new${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/racket-detail${`?${string}` | `#${string}` | ''}` | `/rackets${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/best-racket`; params?: Router.UnknownInputParams; } | { pathname: `/compare-rackets`; params?: Router.UnknownInputParams; } | { pathname: `/faq`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/index_new`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/racket-detail`; params?: Router.UnknownInputParams; } | { pathname: `/rackets`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
